---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

# NOTE: The Packit copr_build tasks help to check if every commit builds on
# supported Fedora and CentOS Stream arches.
# They do not block the current Cirrus-based workflow.

# Build targets can be found at:
# https://copr.fedorainfracloud.org/coprs/rhcontainerbot/packit-builds/

specfile_path: skopeo.spec

jobs:
  - job: copr_build
    trigger: pull_request
    owner: rhcontainerbot
    project: packit-builds
    enable_net: true
    srpm_build_deps:
      - make
      - rpkg
    actions:
      post-upstream-clone:
        - "rpkg spec --outdir ./"
      fix-spec-file:
        - "bash .packit.sh"
