#!/bin/bash
#
# run-tests - simple wrapper allowing shortcuts on invocation
#

TEST_DIR=$(dirname $0)
TESTS=$TEST_DIR

for i; do
    case "$i" in
        *.bats)    TESTS=$i ;;
        *)         TESTS=$(echo $TEST_DIR/*$i*.bats) ;;
    esac
done

bats $TESTS
