#!/bin/bash
set -e

bundle_test_integration() {
	go_test_dir ./integration
}

# subshell so that we can export PATH without breaking other things
(
	make PREFIX=/usr install
	bundle_test_integration
) 2>&1
