---

# See also: https://github.com/containers/podman/blob/main/.github/workflows/rerun_cirrus_cron.yml

on:
  # Note: This only applies to the default branch.
  schedule:
    # N/B: This should correspond to a period slightly after
    # the last job finishes running.  See job defs. at:
    # https://cirrus-ci.com/settings/repository/6706677464432640
    - cron:  '01 01 * * 1-5'
  # Debug: Allow triggering job manually in github-actions WebUI
  workflow_dispatch: {}

jobs:
  # Ref: https://docs.github.com/en/actions/using-workflows/reusing-workflows
  call_cron_rerun:
    uses: containers/podman/.github/workflows/rerun_cirrus_cron.yml@main
    secrets: inherit
